# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiman < Formula
  desc "Agent Inventory Manager — manage AI agent skills and MCP servers across Claude Code, Cursor, Codex"
  homepage "https://github.com/axsmak/aim"
  version "0.5.1-rc1"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/axsmak/aim/releases/download/v0.5.1-rc1/aiman_0.5.1-rc1_darwin_amd64.tar.gz"
    sha256 "687464fc1fd2fbde21914f0d8517948b5cd5cf662933aa92995429f493ba74db"

    define_method(:install) do
      bin.install "aiman"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/axsmak/aim/releases/download/v0.5.1-rc1/aiman_0.5.1-rc1_darwin_arm64.tar.gz"
    sha256 "43dcbe996c6bf12516a72f431cdae51ca51fca05aa8385df6933c80440a84548"

    define_method(:install) do
      bin.install "aiman"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aiman --version")
  end
end
