# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiman < Formula
  desc "Agent Inventory Manager — manage AI agent skills and MCP servers across Claude Code, Cursor, Codex"
  homepage "https://github.com/axsmak/aim"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/axsmak/aim/releases/download/v0.5.3/aiman_darwin_amd64.tar.gz"
      sha256 "1344db2c1f29ea209dc3011197ebae029d4ed4e98e47dbbe226800256b864975"

      define_method(:install) do
        bin.install "aiman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/axsmak/aim/releases/download/v0.5.3/aiman_darwin_arm64.tar.gz"
      sha256 "8b1248f1853ed9a800608ffc318d487c2d3d4296cb8130800167f9f28b5b9d52"

      define_method(:install) do
        bin.install "aiman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/axsmak/aim/releases/download/v0.5.3/aiman_linux_amd64.tar.gz"
      sha256 "319ff960c7aed99fa55b1573dfcf68669b58c7893316dff371e4055235da96e6"
      define_method(:install) do
        bin.install "aiman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/axsmak/aim/releases/download/v0.5.3/aiman_linux_arm64.tar.gz"
      sha256 "50e49a8da4535c16239d290a5b5a422627c671226567d3d3ff376fbb9a8dcd06"
      define_method(:install) do
        bin.install "aiman"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aiman --version")
  end
end
